server:
  port: 8000

spring:
  profiles:
    active: dev
    # local develop product
  datasource:
    url: jdbc:mysql://hoons-aws-db-dev.cttkkceqgfsb.ap-northeast-2.rds.amazonaws.com:3306/triptale
    username: hst
    password: hst123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 115MB

springdoc:
  api-docs:
    path: /api-docs/triptale-be
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /content/**
    - /admin/**
    - /system/**

app:
  fe-service-url: http://localhost:3000
  file:
    storage: fs
    upload-dir: ${user.home}/triptale/files
  security:
    token-secret: 926D96C90030DD58429D2751AC1BDBBC
    token-expirationMs: 864000000 # 10 days
    public-paths:
      # basic web resources
      - /
      - /error
      - /favicon.ico
      - /**/*.png
      - /**/*.gif
      - /**/*.svg
      - /**/*.jpg
      - /**/*.html
      - /**/*.css
      - /**/*.js
      # authentication apis
      - /oauth2/**
      # documentation paths
      - /api-docs
      - /api-docs/**
      - /swagger-ui/**
      - /swagger-ui.html
      # Public apis
      - /system/storage/files/**
      # admin devtools api
      - /admin/devtools/issueToken/**