server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://hoons-aws-db-dev.cttkkceqgfsb.ap-northeast-2.rds.amazonaws.com:3306/triptale
    username: hst
    password: hst123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app:
  security:
    public-apis: /login/**

---
spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true