server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://hoons-aws-db-dev.cttkkceqgfsb.ap-northeast-2.rds.amazonaws.com:3306/triptale
    username: hst
    password: hst123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app:
  security:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMs: 864000000 # 10 days
    public-paths:
      # basic web resources
      - /
      - /error
      - /favicon.ico
      - /**/*.png
      - /**/*.gif
      - /**/*.svg
      - /**/*.jpg
      - /**/*.html
      - /**/*.css
      - /**/*.js
      # application apis
      - /api/oauth2/**

---
spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  fe-service-url: http://localhost:3000
