# Server properties
server:
  port: 8000

# Spring properties
spring:
  profiles:
    active: local
  application:
    name: triptale-api
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 115MB
  cache:
    jcache:
      config: classpath:ehcache.xml

# OpenAPI properties
springdoc:
  api-docs:
    path: /api-docs/triptale-be
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /content/**
    - /admin/**
    - /system/**

# Application properties
app:
  security:
    token-secret: 926D96C90030DD58429D2751AC1BDBBC
    token-expirationMs: 864000000 # 10 days
    public-paths:
      defaults:
        # basic web resources
        - /
        - /error
        - /favicon.ico
        - /**/*.png
        - /**/*.gif
        - /**/*.svg
        - /**/*.jpg
        - /**/*.html
        - /**/*.css
        - /**/*.js
        # authentication apis
        - /oauth2/**
        # documentation paths
        - /api-docs
        - /api-docs/**
        - /swagger-ui/**
        - /swagger-ui.html
        # Public apis
        - /system/storage/files/**
        - /content/weather/**
---
spring:
  profiles: develop
  datasource:
    url: jdbc:mysql://hoons-aws-db-dev.cttkkceqgfsb.ap-northeast-2.rds.amazonaws.com:3306/triptale
    username: hst
    password: hst123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  fe-service-url: http://localhost:3000
  file:
    storage: fs
    upload-dir: ${user.home}/triptale/files
  security:
    public-paths:
      optionals:
        - /system/devtools/issue-token/**

---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://hoons-aws-db-dev.cttkkceqgfsb.ap-northeast-2.rds.amazonaws.com:3306/triptale
    username: hst
    password: hst123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false

app:
  fe-service-url: https://triptale.netlify.app
  file:
    storage: fs
    upload-dir: ${user.home}/triptale/files